-- Generated by Oracle SQL Developer Data Modeler 3.0.0.660.660
--   at:        2011-01-07 13:27:07 GMT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g





CREATE OR REPLACE TYPE ADHEADER_TYP 
;
/




CREATE OR REPLACE TYPE TEXTDOC_TYP 
;
/




CREATE OR REPLACE TYPE TEXTDOC_TAB 
    IS TABLE OF UNKNOWN 
;
/




CREATE OR REPLACE TYPE ADHEADER_TYP 
    AS OBJECT 
    ( 
        HEADER_NAME VARCHAR2 (256) , 
        CREATION_DATE DATE , 
        HEADER_TEXT VARCHAR2 (1024) , 
        LOGO BLOB 
    ) FINAL 
;
/




CREATE OR REPLACE TYPE TEXTDOC_TYP 
    AS OBJECT 
    ( 
        DOCUMENT_TYP VARCHAR2 (32) , 
        FORMATTED_DOC BLOB 
    ) FINAL 
;
/


CREATE TABLE PM.ONLINE_MEDIA 
    ( 
     PRODUCT_ID NUMBER (6)  NOT NULL , 
     PRODUCT_PHOTO ORDSYS.ORDImage , 
     PRODUCT_PHOTO_SIGNATURE ORDSYS.ORDImageSignature , 
     PRODUCT_THUMBNAIL ORDSYS.ORDImage , 
     PRODUCT_VIDEO ORDSYS.ORDVideo , 
     PRODUCT_AUDIO ORDSYS.ORDAudio , 
     PRODUCT_TEXT CLOB , 
     PRODUCT_TESTIMONIALS ORDSYS.ORDDoc 
    ) 
        TABLESPACE EXAMPLE 
        NOLOGGING 
    LOB ( ""PRODUCT_PHOTO_SIGNATURE"".""SIGNATURE"" ) STORE AS 
        ( 
        TABLESPACE EXAMPLE 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW
        NOCACHE NOLOGGING 
    ) 
    LOB ( ""PRODUCT_THUMBNAIL"".""SOURCE"".""LOCALDATA"" ) STORE AS 
        ( 
        TABLESPACE EXAMPLE 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW
        NOCACHE NOLOGGING 
    ) 
    LOB ( ""PRODUCT_VIDEO"".""SOURCE"".""LOCALDATA"" ) STORE AS 
        ( 
        TABLESPACE EXAMPLE 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW
        NOCACHE NOLOGGING 
    ) 
    LOB ( ""PRODUCT_VIDEO"".""COMMENTS"" ) STORE AS 
        ( 
        TABLESPACE EXAMPLE 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW
        NOCACHE NOLOGGING 
    ) 
    LOB ( ""PRODUCT_AUDIO"".""SOURCE"".""LOCALDATA"" ) STORE AS 
        ( 
        TABLESPACE EXAMPLE 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW
        NOCACHE NOLOGGING 
    ) 
    LOB ( ""PRODUCT_AUDIO"".""COMMENTS"" ) STORE AS 
        ( 
        TABLESPACE EXAMPLE 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW
        NOCACHE NOLOGGING 
    ) 
    LOB ( PRODUCT_TEXT ) STORE AS 
        ( 
        TABLESPACE EXAMPLE 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW
        NOCACHE NOLOGGING 
    ) 
    LOB ( ""PRODUCT_TESTIMONIALS"".""SOURCE"".""LOCALDATA"" ) STORE AS 
        ( 
        TABLESPACE EXAMPLE 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW
        NOCACHE NOLOGGING 
    ) 
    LOB ( ""PRODUCT_TESTIMONIALS"".""COMMENTS"" ) STORE AS 
        ( 
        TABLESPACE EXAMPLE 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW
        NOCACHE NOLOGGING 
    ) 
    LOB ( ""PRODUCT_PHOTO"".""SOURCE"".""LOCALDATA"" ) STORE AS 
        ( 
        TABLESPACE EXAMPLE 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW
        NOCACHE NOLOGGING 
    ) 
;


CREATE UNIQUE INDEX PM.ONLINEMEDIA_PK ON PM.ONLINE_MEDIA 
    ( 
     PRODUCT_ID ASC 
    ) 
    TABLESPACE EXAMPLE 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    NOLOGGING 
    NOCOMPRESS 
    NOPARALLEL 
;

ALTER TABLE PM.ONLINE_MEDIA 
    ADD CONSTRAINT ONLINEMEDIA__PK PRIMARY KEY ( PRODUCT_ID ) 
    USING INDEX PM.ONLINEMEDIA_PK ;


CREATE TABLE PM.PRINT_MEDIA 
    ( 
     PRODUCT_ID NUMBER (6)  NOT NULL , 
     AD_ID NUMBER (6)  NOT NULL , 
     AD_COMPOSITE BLOB , 
     AD_SOURCETEXT CLOB , 
     AD_FINALTEXT CLOB , 
     AD_FLTEXTN NCLOB , 
     AD_TEXTDOCS_NTAB TEXTDOC_TAB , 
     AD_PHOTO BLOB , 
     AD_GRAPHIC BFILE , 
     AD_HEADER ADHEADER_TYP 
    ) 
        TABLESPACE EXAMPLE 
        NOLOGGING 
    LOB ( ""AD_HEADER"".""LOGO"" ) STORE AS 
        ( 
        TABLESPACE EXAMPLE 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW
        NOCACHE NOLOGGING 
    ) 
    LOB ( AD_COMPOSITE ) STORE AS 
        ( 
        TABLESPACE EXAMPLE 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW
        NOCACHE NOLOGGING 
    ) 
    LOB ( AD_SOURCETEXT ) STORE AS 
        ( 
        TABLESPACE EXAMPLE 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW
        NOCACHE NOLOGGING 
    ) 
    LOB ( AD_FINALTEXT ) STORE AS 
        ( 
        TABLESPACE EXAMPLE 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW
        NOCACHE NOLOGGING 
    ) 
    LOB ( AD_FLTEXTN ) STORE AS 
        ( 
        TABLESPACE EXAMPLE 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW
        NOCACHE NOLOGGING 
    ) 
    LOB ( AD_PHOTO ) STORE AS 
        ( 
        TABLESPACE EXAMPLE 
        STORAGE ( 
            PCTINCREASE 0 
            MINEXTENTS 1 
            MAXEXTENTS UNLIMITED 
            FREELISTS 1 
            BUFFER_POOL DEFAULT 
        ) 
        CHUNK 8192 
        RETENTION 
        ENABLE STORAGE IN ROW
        NOCACHE NOLOGGING 
    ) 
;


CREATE UNIQUE INDEX PM.PRINTMEDIA_PK ON PM.PRINT_MEDIA 
    ( 
     PRODUCT_ID ASC , 
     AD_ID ASC 
    ) 
    TABLESPACE EXAMPLE 
    PCTFREE 10 
    MAXTRANS 255 
    STORAGE ( 
        INITIAL 65536 
        NEXT 1048576 
        PCTINCREASE 0 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT ) 
    NOLOGGING 
    NOCOMPRESS 
    NOPARALLEL 
;
CREATE UNIQUE INDEX PM.IX_SYS_C005190 ON PM.PRINT_MEDIA 
    ( 
     AD_TEXTDOCS_NTAB ASC 
    ) 
    LOGGING 
    NOCOMPRESS 
    NOPARALLEL 
;

ALTER TABLE PM.PRINT_MEDIA 
    ADD CONSTRAINT PRINTMEDIA__PK PRIMARY KEY ( PRODUCT_ID, AD_ID ) 
    USING INDEX PM.PRINTMEDIA_PK ;






-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             2
-- CREATE INDEX                             3
-- ALTER TABLE                              2
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- CREATE STRUCTURED TYPE                   2
-- CREATE COLLECTION TYPE                   1
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
